# Generated by Django 5.2.8 on 2025-11-26 14:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_remove_company_partners_partner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='deactivated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Desativado em'),
        ),
        migrations.AddField(
            model_name='company',
            name='deactivated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies_deactivated', to=settings.AUTH_USER_MODEL, verbose_name='Desativado por'),
        ),
        migrations.AddField(
            model_name='company',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Ativo?'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='companies.company'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Entrou em'),
        ),
    ]
