# Generated by Django 5.2.8 on 2025-11-26 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_company_deactivated_at_company_deactivated_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Ativo? '),
        ),
    ]
